{
 "title": "Wetterstationen",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "Station",
    "label": "Wetterstation",
    "query": "select StationName from Wetterstationen"
   }
  ]
 },
 "panels": [
  {
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 0 },
   "options": {
    "content": "&nbsp;\n\nNeuster Datensatz: {{date_formated}} {{time_formated}}\n\n"
   },
   "targets": [
    {
     "rawSql": "SELECT TIME_FORMAT(CONVERT_TZ(`timedate`, @@session.time_zone, '+01:00'), \"%H:%i:%s\") AS time_formated, Date_Format(timedate, \"%d.%m.%Y\") AS date_formated\nFROM messwerte\nWHERE StationName = '$Station'\nORDER BY timedate DESC\nLIMIT 0,1"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 14, "x": 5, "y": 0 },
   "options": {
    "content": "<div>\r\n<h2 style=\"text-align: center;\">&nbsp;</h2>\r\n<h2 style=\"text-align: center;\"><strong>Messwerte</strong></h2>\r\n</div>\r\n<p><strong>&nbsp;</strong></p>"
   },
   "targets": [
    {
     "rawSql": "SELECT\n  timedate AS \"time\",\n  id\nFROM messwerte\nWHERE\n  $__timeFilter(timedate)\nORDER BY timedate"
    }
   ]
  },
  {
   "title": "Temperatur",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timedate AS \"time\",\n  temp\nFROM messwerte\nWHERE\n  $__timeFilter(timedate) AND\n  StationName = '$Station'\nORDER BY timedate"
    }
   ]
  },
  {
   "title": "Luftfeuchtigkeit",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timedate AS \"time\",\n  humidity\nFROM messwerte\nWHERE\n  $__timeFilter(timedate) AND\n  StationName = '$Station'\nORDER BY timedate"
    }
   ]
  },
  {
   "title": "Luftqualität",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "kOhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timedate AS \"time\",\n  gas\nFROM messwerte\nWHERE\n  $__timeFilter(timedate) AND\n  StationName = '$Station'\nORDER BY timedate"
    }
   ]
  },
  {
   "title": "Luftdruck",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timedate AS \"time\",\n  presure\nFROM messwerte\nWHERE\n  $__timeFilter(timedate) AND\n  StationName = '$Station'\nORDER BY timedate"
    }
   ]
  },
  {
   "title": "Temperatur",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT\n  timedate AS \"time\",\n  temp\nFROM messwerte\nWHERE\n  $__timeFilter(timedate) AND\n  StationName = '$Station'\nORDER BY timedate"
    }
   ]
  },
  {
   "title": "Luftqualität",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "kOhms" } },
   "targets": [
    {
     "rawSql": "SELECT\n  timedate AS \"time\",\n  gas\nFROM messwerte\nWHERE\n  $__timeFilter(timedate) AND\n  StationName = '$Station'\nORDER BY timedate"
    }
   ]
  },
  {
   "title": "Luftfeuchtigkeit",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\n  timedate AS \"time\",\n  humidity\nFROM messwerte\nWHERE\n  $__timeFilter(timedate) AND\n  StationName = '$Station'\nORDER BY timedate"
    }
   ]
  },
  {
   "title": "Luftdruck",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    {
     "rawSql": "SELECT\n  timedate AS \"time\",\n  presure\nFROM messwerte\nWHERE\n  $__timeFilter(timedate) AND\n  StationName = '$Station'\nORDER BY timedate"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 12, "x": 6, "y": 26 },
   "options": {
    "content": "<div>\r\n<h2 style=\"text-align: center;\">&nbsp;</h2>\r\n<h2 style=\"text-align: center;\"><strong>Wettersensor&nbsp;Info</strong></h2>\r\n</div>\r\n<p><strong>&nbsp;</strong></p>"
   },
   "targets": [
    {
     "rawSql": "SELECT\n  timedate AS \"time\",\n  id\nFROM messwerte\nWHERE\n  $__timeFilter(timedate)\nORDER BY timedate"
    }
   ]
  },
  {
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "options": {
    "content": "## {{StationName}}\n#### {{Address}} {{StreetNumber}} {{City}} {{PLZ}}\n\n<pre>\nWiFI SSID:           {{SSID}}\nWiFI RSSI:           {{rssi}}\nFree Heap:           {{heap_free}} KByte\nHeap Fragmentierung: {{heap_fragmentation}}%\nLetztes Update:      {{date_formated}} {{time_formated}}\n</pre>"
   },
   "targets": [
    {
     "rawSql": "SELECT Wetterstationen.StationName, Wetterstationen.StreetNumber, Wetterstationen.City, Wetterstationen.PLZ, Wetterstationen.Address, hw_diagnostics.SSID,hw_diagnostics.rssi, hw_diagnostics.heap_fragmentation, hw_diagnostics.heap_free,  TIME_FORMAT(CONVERT_TZ(`timedate`, @@session.time_zone, '+01:00'), \"%H:%i:%s\") AS time_formated, Date_Format(timedate, \"%d.%m.%Y\") AS date_formated\nFROM hw_diagnostics\nINNER JOIN Wetterstationen ON hw_diagnostics.StationName=Wetterstationen.StationName\nWHERE Wetterstationen.StationName = '$Station'\nORDER BY timedate DESC\nLIMIT 0,1\n  \n  \n  "
    }
   ]
  },
  {
   "title": "WiFi Qualität",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "rawSql": "SELECT\n  timedate AS \"time\",\n  rssi\nFROM hw_diagnostics\nWHERE\n  $__timeFilter(timedate) AND\n  StationName = '$Station'\nORDER BY timedate"
    }
   ]
  },
  {
   "title": "Free Heap Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "rawSql": "SELECT\n  timedate AS \"time\",\n  heap_free\nFROM hw_diagnostics\nWHERE\n  $__timeFilter(timedate) AND\n  StationName = '$Station'\nORDER BY timedate"
    }
   ]
  },
  {
   "title": "Heap Memory Fragmentation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\n  timedate AS \"time\",\n  heap_fragmentation\nFROM hw_diagnostics\nWHERE\n  $__timeFilter(timedate) AND\n  StationName = '$Station'\nORDER BY timedate"
    }
   ]
  }
 ]
}